# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Rookie
            image:
        nav:
            - item_name: Github
              item_url: 'https://www.github.com/pjc0247/rookie.lang'
    footer:
        content:
            logo:
                text: Rookie
                image:
            copyright: Copyright &copy; 2018. - pjc0247 <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'http://www.github.com/pjc0247'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
